### ISSUE TITLE
AspNet extension

### ISSUE THREAD

**Issue by andriusfl** [never-test/engine#1]
Allows creating scenarios for asp.net apps. 

**Package**: NeverTest.AspNet

```yaml
state:
  entryPoint: MyApp, MyAssembly
  client: default

scenarios:
  - name: Should allow calling api
    when:
      get: /weatherforecast
    then: httpOk
```
