### ISSUE TITLE
Add support for Testcontainers

### ISSUE THREAD

**Issue by andriusfl** [never-test/engine#4]
```yaml
state:
  entryPoint: MyApp, MyAssembly
  client: default

containers:
  default:
  - image: testcontainers/helloworld:1.1.0
    network: net
    bindings:
      - port: 8080
        client: test # adds client named 'test' into scenario service collection for use in http acts
        configKey: helloworld:url # replaces config key in asp.net app

scenarios:
  - name: Should allow calling directly
    when:
      get: 
        url: /
        client: test
    then: httpOk

  - name: Should allow calling via asp.net app
    when:
      get:   /test
    then: httpOk
```
